/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HealthRouteImport } from './routes/health'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as toolsRouteRouteImport } from './routes/(tools)/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedLoansRouteImport } from './routes/_authenticated/loans'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as toolsUuidGeneratorRouteImport } from './routes/(tools)/uuid-generator'
import { Route as toolsSecretGeneratorRouteImport } from './routes/(tools)/secret-generator'
import { Route as toolsPasswordGeneratorRouteImport } from './routes/(tools)/password-generator'
import { Route as AuthenticatedLoansIndexRouteImport } from './routes/_authenticated/loans.index'
import { Route as AuthenticatedLoansLoanIdRouteImport } from './routes/_authenticated/loans.$loanId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const toolsRouteRoute = toolsRouteRouteImport.update({
  id: '/(tools)',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedLoansRoute = AuthenticatedLoansRouteImport.update({
  id: '/loans',
  path: '/loans',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const toolsUuidGeneratorRoute = toolsUuidGeneratorRouteImport.update({
  id: '/uuid-generator',
  path: '/uuid-generator',
  getParentRoute: () => toolsRouteRoute,
} as any)
const toolsSecretGeneratorRoute = toolsSecretGeneratorRouteImport.update({
  id: '/secret-generator',
  path: '/secret-generator',
  getParentRoute: () => toolsRouteRoute,
} as any)
const toolsPasswordGeneratorRoute = toolsPasswordGeneratorRouteImport.update({
  id: '/password-generator',
  path: '/password-generator',
  getParentRoute: () => toolsRouteRoute,
} as any)
const AuthenticatedLoansIndexRoute = AuthenticatedLoansIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedLoansRoute,
} as any)
const AuthenticatedLoansLoanIdRoute =
  AuthenticatedLoansLoanIdRouteImport.update({
    id: '/$loanId',
    path: '/$loanId',
    getParentRoute: () => AuthenticatedLoansRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/health': typeof HealthRoute
  '/login': typeof LoginRoute
  '/password-generator': typeof toolsPasswordGeneratorRoute
  '/secret-generator': typeof toolsSecretGeneratorRoute
  '/uuid-generator': typeof toolsUuidGeneratorRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/loans': typeof AuthenticatedLoansRouteWithChildren
  '/loans/$loanId': typeof AuthenticatedLoansLoanIdRoute
  '/loans/': typeof AuthenticatedLoansIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/health': typeof HealthRoute
  '/login': typeof LoginRoute
  '/password-generator': typeof toolsPasswordGeneratorRoute
  '/secret-generator': typeof toolsSecretGeneratorRoute
  '/uuid-generator': typeof toolsUuidGeneratorRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/loans/$loanId': typeof AuthenticatedLoansLoanIdRoute
  '/loans': typeof AuthenticatedLoansIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(tools)': typeof toolsRouteRouteWithChildren
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/health': typeof HealthRoute
  '/login': typeof LoginRoute
  '/(tools)/password-generator': typeof toolsPasswordGeneratorRoute
  '/(tools)/secret-generator': typeof toolsSecretGeneratorRoute
  '/(tools)/uuid-generator': typeof toolsUuidGeneratorRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/loans': typeof AuthenticatedLoansRouteWithChildren
  '/_authenticated/loans/$loanId': typeof AuthenticatedLoansLoanIdRoute
  '/_authenticated/loans/': typeof AuthenticatedLoansIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/health'
    | '/login'
    | '/password-generator'
    | '/secret-generator'
    | '/uuid-generator'
    | '/dashboard'
    | '/loans'
    | '/loans/$loanId'
    | '/loans/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/health'
    | '/login'
    | '/password-generator'
    | '/secret-generator'
    | '/uuid-generator'
    | '/dashboard'
    | '/loans/$loanId'
    | '/loans'
  id:
    | '__root__'
    | '/'
    | '/(tools)'
    | '/_authenticated'
    | '/health'
    | '/login'
    | '/(tools)/password-generator'
    | '/(tools)/secret-generator'
    | '/(tools)/uuid-generator'
    | '/_authenticated/dashboard'
    | '/_authenticated/loans'
    | '/_authenticated/loans/$loanId'
    | '/_authenticated/loans/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  toolsRouteRoute: typeof toolsRouteRouteWithChildren
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  HealthRoute: typeof HealthRoute
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(tools)': {
      id: '/(tools)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof toolsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/loans': {
      id: '/_authenticated/loans'
      path: '/loans'
      fullPath: '/loans'
      preLoaderRoute: typeof AuthenticatedLoansRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/(tools)/uuid-generator': {
      id: '/(tools)/uuid-generator'
      path: '/uuid-generator'
      fullPath: '/uuid-generator'
      preLoaderRoute: typeof toolsUuidGeneratorRouteImport
      parentRoute: typeof toolsRouteRoute
    }
    '/(tools)/secret-generator': {
      id: '/(tools)/secret-generator'
      path: '/secret-generator'
      fullPath: '/secret-generator'
      preLoaderRoute: typeof toolsSecretGeneratorRouteImport
      parentRoute: typeof toolsRouteRoute
    }
    '/(tools)/password-generator': {
      id: '/(tools)/password-generator'
      path: '/password-generator'
      fullPath: '/password-generator'
      preLoaderRoute: typeof toolsPasswordGeneratorRouteImport
      parentRoute: typeof toolsRouteRoute
    }
    '/_authenticated/loans/': {
      id: '/_authenticated/loans/'
      path: '/'
      fullPath: '/loans/'
      preLoaderRoute: typeof AuthenticatedLoansIndexRouteImport
      parentRoute: typeof AuthenticatedLoansRoute
    }
    '/_authenticated/loans/$loanId': {
      id: '/_authenticated/loans/$loanId'
      path: '/$loanId'
      fullPath: '/loans/$loanId'
      preLoaderRoute: typeof AuthenticatedLoansLoanIdRouteImport
      parentRoute: typeof AuthenticatedLoansRoute
    }
  }
}

interface toolsRouteRouteChildren {
  toolsPasswordGeneratorRoute: typeof toolsPasswordGeneratorRoute
  toolsSecretGeneratorRoute: typeof toolsSecretGeneratorRoute
  toolsUuidGeneratorRoute: typeof toolsUuidGeneratorRoute
}

const toolsRouteRouteChildren: toolsRouteRouteChildren = {
  toolsPasswordGeneratorRoute: toolsPasswordGeneratorRoute,
  toolsSecretGeneratorRoute: toolsSecretGeneratorRoute,
  toolsUuidGeneratorRoute: toolsUuidGeneratorRoute,
}

const toolsRouteRouteWithChildren = toolsRouteRoute._addFileChildren(
  toolsRouteRouteChildren,
)

interface AuthenticatedLoansRouteChildren {
  AuthenticatedLoansLoanIdRoute: typeof AuthenticatedLoansLoanIdRoute
  AuthenticatedLoansIndexRoute: typeof AuthenticatedLoansIndexRoute
}

const AuthenticatedLoansRouteChildren: AuthenticatedLoansRouteChildren = {
  AuthenticatedLoansLoanIdRoute: AuthenticatedLoansLoanIdRoute,
  AuthenticatedLoansIndexRoute: AuthenticatedLoansIndexRoute,
}

const AuthenticatedLoansRouteWithChildren =
  AuthenticatedLoansRoute._addFileChildren(AuthenticatedLoansRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedLoansRoute: typeof AuthenticatedLoansRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedLoansRoute: AuthenticatedLoansRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  toolsRouteRoute: toolsRouteRouteWithChildren,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  HealthRoute: HealthRoute,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
