/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HealthRouteImport } from './routes/health'
import { Route as PublicRouteRouteImport } from './routes/_public/route'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as toolsRouteRouteImport } from './routes/(tools)/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as toolsUuidGeneratorRouteImport } from './routes/(tools)/uuid-generator'
import { Route as toolsSecretGeneratorRouteImport } from './routes/(tools)/secret-generator'
import { Route as toolsPasswordGeneratorRouteImport } from './routes/(tools)/password-generator'
import { Route as AuthenticatedSettingsRouteRouteImport } from './routes/_authenticated/settings/route'
import { Route as PublicDocumentsTokenRouteImport } from './routes/_public/documents/$token'
import { Route as AuthenticatedSettingsDocumentsRouteImport } from './routes/_authenticated/settings/documents'
import { Route as AuthenticatedloansLoansRouteImport } from './routes/_authenticated/(loans)/loans'
import { Route as AuthenticatedSettingsDocumentsIndexRouteImport } from './routes/_authenticated/settings/documents.index'
import { Route as AuthenticatedloansLoansIndexRouteImport } from './routes/_authenticated/(loans)/loans.index'
import { Route as AuthenticatedSettingsDocumentsDocumentIdRouteImport } from './routes/_authenticated/settings/documents.$documentId'
import { Route as AuthenticatedloansLoansLoanIdRouteImport } from './routes/_authenticated/(loans)/loans.$loanId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRouteRoute = PublicRouteRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const toolsRouteRoute = toolsRouteRouteImport.update({
  id: '/(tools)',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const toolsUuidGeneratorRoute = toolsUuidGeneratorRouteImport.update({
  id: '/uuid-generator',
  path: '/uuid-generator',
  getParentRoute: () => toolsRouteRoute,
} as any)
const toolsSecretGeneratorRoute = toolsSecretGeneratorRouteImport.update({
  id: '/secret-generator',
  path: '/secret-generator',
  getParentRoute: () => toolsRouteRoute,
} as any)
const toolsPasswordGeneratorRoute = toolsPasswordGeneratorRouteImport.update({
  id: '/password-generator',
  path: '/password-generator',
  getParentRoute: () => toolsRouteRoute,
} as any)
const AuthenticatedSettingsRouteRoute =
  AuthenticatedSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const PublicDocumentsTokenRoute = PublicDocumentsTokenRouteImport.update({
  id: '/documents/$token',
  path: '/documents/$token',
  getParentRoute: () => PublicRouteRoute,
} as any)
const AuthenticatedSettingsDocumentsRoute =
  AuthenticatedSettingsDocumentsRouteImport.update({
    id: '/documents',
    path: '/documents',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedloansLoansRoute = AuthenticatedloansLoansRouteImport.update({
  id: '/(loans)/loans',
  path: '/loans',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsDocumentsIndexRoute =
  AuthenticatedSettingsDocumentsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsDocumentsRoute,
  } as any)
const AuthenticatedloansLoansIndexRoute =
  AuthenticatedloansLoansIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedloansLoansRoute,
  } as any)
const AuthenticatedSettingsDocumentsDocumentIdRoute =
  AuthenticatedSettingsDocumentsDocumentIdRouteImport.update({
    id: '/$documentId',
    path: '/$documentId',
    getParentRoute: () => AuthenticatedSettingsDocumentsRoute,
  } as any)
const AuthenticatedloansLoansLoanIdRoute =
  AuthenticatedloansLoansLoanIdRouteImport.update({
    id: '/$loanId',
    path: '/$loanId',
    getParentRoute: () => AuthenticatedloansLoansRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/health': typeof HealthRoute
  '/login': typeof LoginRoute
  '/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/password-generator': typeof toolsPasswordGeneratorRoute
  '/secret-generator': typeof toolsSecretGeneratorRoute
  '/uuid-generator': typeof toolsUuidGeneratorRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/loans': typeof AuthenticatedloansLoansRouteWithChildren
  '/settings/documents': typeof AuthenticatedSettingsDocumentsRouteWithChildren
  '/documents/$token': typeof PublicDocumentsTokenRoute
  '/loans/$loanId': typeof AuthenticatedloansLoansLoanIdRoute
  '/settings/documents/$documentId': typeof AuthenticatedSettingsDocumentsDocumentIdRoute
  '/loans/': typeof AuthenticatedloansLoansIndexRoute
  '/settings/documents/': typeof AuthenticatedSettingsDocumentsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/health': typeof HealthRoute
  '/login': typeof LoginRoute
  '/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/password-generator': typeof toolsPasswordGeneratorRoute
  '/secret-generator': typeof toolsSecretGeneratorRoute
  '/uuid-generator': typeof toolsUuidGeneratorRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/documents/$token': typeof PublicDocumentsTokenRoute
  '/loans/$loanId': typeof AuthenticatedloansLoansLoanIdRoute
  '/settings/documents/$documentId': typeof AuthenticatedSettingsDocumentsDocumentIdRoute
  '/loans': typeof AuthenticatedloansLoansIndexRoute
  '/settings/documents': typeof AuthenticatedSettingsDocumentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(tools)': typeof toolsRouteRouteWithChildren
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_public': typeof PublicRouteRouteWithChildren
  '/health': typeof HealthRoute
  '/login': typeof LoginRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/(tools)/password-generator': typeof toolsPasswordGeneratorRoute
  '/(tools)/secret-generator': typeof toolsSecretGeneratorRoute
  '/(tools)/uuid-generator': typeof toolsUuidGeneratorRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/(loans)/loans': typeof AuthenticatedloansLoansRouteWithChildren
  '/_authenticated/settings/documents': typeof AuthenticatedSettingsDocumentsRouteWithChildren
  '/_public/documents/$token': typeof PublicDocumentsTokenRoute
  '/_authenticated/(loans)/loans/$loanId': typeof AuthenticatedloansLoansLoanIdRoute
  '/_authenticated/settings/documents/$documentId': typeof AuthenticatedSettingsDocumentsDocumentIdRoute
  '/_authenticated/(loans)/loans/': typeof AuthenticatedloansLoansIndexRoute
  '/_authenticated/settings/documents/': typeof AuthenticatedSettingsDocumentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/health'
    | '/login'
    | '/settings'
    | '/password-generator'
    | '/secret-generator'
    | '/uuid-generator'
    | '/dashboard'
    | '/loans'
    | '/settings/documents'
    | '/documents/$token'
    | '/loans/$loanId'
    | '/settings/documents/$documentId'
    | '/loans/'
    | '/settings/documents/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/health'
    | '/login'
    | '/settings'
    | '/password-generator'
    | '/secret-generator'
    | '/uuid-generator'
    | '/dashboard'
    | '/documents/$token'
    | '/loans/$loanId'
    | '/settings/documents/$documentId'
    | '/loans'
    | '/settings/documents'
  id:
    | '__root__'
    | '/'
    | '/(tools)'
    | '/_authenticated'
    | '/_public'
    | '/health'
    | '/login'
    | '/_authenticated/settings'
    | '/(tools)/password-generator'
    | '/(tools)/secret-generator'
    | '/(tools)/uuid-generator'
    | '/_authenticated/dashboard'
    | '/_authenticated/(loans)/loans'
    | '/_authenticated/settings/documents'
    | '/_public/documents/$token'
    | '/_authenticated/(loans)/loans/$loanId'
    | '/_authenticated/settings/documents/$documentId'
    | '/_authenticated/(loans)/loans/'
    | '/_authenticated/settings/documents/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  toolsRouteRoute: typeof toolsRouteRouteWithChildren
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  PublicRouteRoute: typeof PublicRouteRouteWithChildren
  HealthRoute: typeof HealthRoute
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(tools)': {
      id: '/(tools)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof toolsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/(tools)/uuid-generator': {
      id: '/(tools)/uuid-generator'
      path: '/uuid-generator'
      fullPath: '/uuid-generator'
      preLoaderRoute: typeof toolsUuidGeneratorRouteImport
      parentRoute: typeof toolsRouteRoute
    }
    '/(tools)/secret-generator': {
      id: '/(tools)/secret-generator'
      path: '/secret-generator'
      fullPath: '/secret-generator'
      preLoaderRoute: typeof toolsSecretGeneratorRouteImport
      parentRoute: typeof toolsRouteRoute
    }
    '/(tools)/password-generator': {
      id: '/(tools)/password-generator'
      path: '/password-generator'
      fullPath: '/password-generator'
      preLoaderRoute: typeof toolsPasswordGeneratorRouteImport
      parentRoute: typeof toolsRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_public/documents/$token': {
      id: '/_public/documents/$token'
      path: '/documents/$token'
      fullPath: '/documents/$token'
      preLoaderRoute: typeof PublicDocumentsTokenRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_authenticated/settings/documents': {
      id: '/_authenticated/settings/documents'
      path: '/documents'
      fullPath: '/settings/documents'
      preLoaderRoute: typeof AuthenticatedSettingsDocumentsRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/(loans)/loans': {
      id: '/_authenticated/(loans)/loans'
      path: '/loans'
      fullPath: '/loans'
      preLoaderRoute: typeof AuthenticatedloansLoansRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/documents/': {
      id: '/_authenticated/settings/documents/'
      path: '/'
      fullPath: '/settings/documents/'
      preLoaderRoute: typeof AuthenticatedSettingsDocumentsIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsDocumentsRoute
    }
    '/_authenticated/(loans)/loans/': {
      id: '/_authenticated/(loans)/loans/'
      path: '/'
      fullPath: '/loans/'
      preLoaderRoute: typeof AuthenticatedloansLoansIndexRouteImport
      parentRoute: typeof AuthenticatedloansLoansRoute
    }
    '/_authenticated/settings/documents/$documentId': {
      id: '/_authenticated/settings/documents/$documentId'
      path: '/$documentId'
      fullPath: '/settings/documents/$documentId'
      preLoaderRoute: typeof AuthenticatedSettingsDocumentsDocumentIdRouteImport
      parentRoute: typeof AuthenticatedSettingsDocumentsRoute
    }
    '/_authenticated/(loans)/loans/$loanId': {
      id: '/_authenticated/(loans)/loans/$loanId'
      path: '/$loanId'
      fullPath: '/loans/$loanId'
      preLoaderRoute: typeof AuthenticatedloansLoansLoanIdRouteImport
      parentRoute: typeof AuthenticatedloansLoansRoute
    }
  }
}

interface toolsRouteRouteChildren {
  toolsPasswordGeneratorRoute: typeof toolsPasswordGeneratorRoute
  toolsSecretGeneratorRoute: typeof toolsSecretGeneratorRoute
  toolsUuidGeneratorRoute: typeof toolsUuidGeneratorRoute
}

const toolsRouteRouteChildren: toolsRouteRouteChildren = {
  toolsPasswordGeneratorRoute: toolsPasswordGeneratorRoute,
  toolsSecretGeneratorRoute: toolsSecretGeneratorRoute,
  toolsUuidGeneratorRoute: toolsUuidGeneratorRoute,
}

const toolsRouteRouteWithChildren = toolsRouteRoute._addFileChildren(
  toolsRouteRouteChildren,
)

interface AuthenticatedSettingsDocumentsRouteChildren {
  AuthenticatedSettingsDocumentsDocumentIdRoute: typeof AuthenticatedSettingsDocumentsDocumentIdRoute
  AuthenticatedSettingsDocumentsIndexRoute: typeof AuthenticatedSettingsDocumentsIndexRoute
}

const AuthenticatedSettingsDocumentsRouteChildren: AuthenticatedSettingsDocumentsRouteChildren =
  {
    AuthenticatedSettingsDocumentsDocumentIdRoute:
      AuthenticatedSettingsDocumentsDocumentIdRoute,
    AuthenticatedSettingsDocumentsIndexRoute:
      AuthenticatedSettingsDocumentsIndexRoute,
  }

const AuthenticatedSettingsDocumentsRouteWithChildren =
  AuthenticatedSettingsDocumentsRoute._addFileChildren(
    AuthenticatedSettingsDocumentsRouteChildren,
  )

interface AuthenticatedSettingsRouteRouteChildren {
  AuthenticatedSettingsDocumentsRoute: typeof AuthenticatedSettingsDocumentsRouteWithChildren
}

const AuthenticatedSettingsRouteRouteChildren: AuthenticatedSettingsRouteRouteChildren =
  {
    AuthenticatedSettingsDocumentsRoute:
      AuthenticatedSettingsDocumentsRouteWithChildren,
  }

const AuthenticatedSettingsRouteRouteWithChildren =
  AuthenticatedSettingsRouteRoute._addFileChildren(
    AuthenticatedSettingsRouteRouteChildren,
  )

interface AuthenticatedloansLoansRouteChildren {
  AuthenticatedloansLoansLoanIdRoute: typeof AuthenticatedloansLoansLoanIdRoute
  AuthenticatedloansLoansIndexRoute: typeof AuthenticatedloansLoansIndexRoute
}

const AuthenticatedloansLoansRouteChildren: AuthenticatedloansLoansRouteChildren =
  {
    AuthenticatedloansLoansLoanIdRoute: AuthenticatedloansLoansLoanIdRoute,
    AuthenticatedloansLoansIndexRoute: AuthenticatedloansLoansIndexRoute,
  }

const AuthenticatedloansLoansRouteWithChildren =
  AuthenticatedloansLoansRoute._addFileChildren(
    AuthenticatedloansLoansRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedSettingsRouteRoute: typeof AuthenticatedSettingsRouteRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedloansLoansRoute: typeof AuthenticatedloansLoansRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedSettingsRouteRoute: AuthenticatedSettingsRouteRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedloansLoansRoute: AuthenticatedloansLoansRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface PublicRouteRouteChildren {
  PublicDocumentsTokenRoute: typeof PublicDocumentsTokenRoute
}

const PublicRouteRouteChildren: PublicRouteRouteChildren = {
  PublicDocumentsTokenRoute: PublicDocumentsTokenRoute,
}

const PublicRouteRouteWithChildren = PublicRouteRoute._addFileChildren(
  PublicRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  toolsRouteRoute: toolsRouteRouteWithChildren,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  PublicRouteRoute: PublicRouteRouteWithChildren,
  HealthRoute: HealthRoute,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
