export enum DocumentType {
  LOAN = 'LOAN',
}

export const DOCUMENT_TYPES = [DocumentType.LOAN] as const;

export enum LoanDocumentLogEventType {
  LINK_CREATED = 'LINK_CREATED',
  LINK_REVOKED = 'LINK_REVOKED',
  LINK_VIEWED = 'LINK_VIEWED',
  LINK_ACCESS_INVALID_OR_EXPIRED = 'LINK_ACCESS_INVALID_OR_EXPIRED',
  DOCUMENT_SIGNED = 'DOCUMENT_SIGNED',
  SIGN_ATTEMPT_INVALID_OR_EXPIRED = 'SIGN_ATTEMPT_INVALID_OR_EXPIRED',
  SIGN_ATTEMPT_DUPLICATE = 'SIGN_ATTEMPT_DUPLICATE',
  SIGN_ATTEMPT_MISSING_SIGNATURE = 'SIGN_ATTEMPT_MISSING_SIGNATURE',
}

export const LOAN_DOCUMENT_LOG_EVENT_TYPES = [
  LoanDocumentLogEventType.LINK_CREATED,
  LoanDocumentLogEventType.LINK_REVOKED,
  LoanDocumentLogEventType.LINK_VIEWED,
  LoanDocumentLogEventType.LINK_ACCESS_INVALID_OR_EXPIRED,
  LoanDocumentLogEventType.DOCUMENT_SIGNED,
  LoanDocumentLogEventType.SIGN_ATTEMPT_INVALID_OR_EXPIRED,
  LoanDocumentLogEventType.SIGN_ATTEMPT_DUPLICATE,
  LoanDocumentLogEventType.SIGN_ATTEMPT_MISSING_SIGNATURE,
] as const;

export enum LoanDocumentLogActorType {
  AUTHENTICATED_USER = 'AUTHENTICATED_USER',
  PUBLIC_LINK_VISITOR = 'PUBLIC_LINK_VISITOR',
}

export const LOAN_DOCUMENT_LOG_ACTOR_TYPES = [
  LoanDocumentLogActorType.AUTHENTICATED_USER,
  LoanDocumentLogActorType.PUBLIC_LINK_VISITOR,
] as const;
